on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: just test
        run: date > generated.txt
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "generated"
          git push
